version: "3.1"
services:
  python:
    # Shows the output from print() in the terminal
    environment:
      - PYTHONUNBUFFERED=1    
    container_name: python_3.9.18_mixhtml
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - C:\web\mixhtml:/app
    networks:
      - mixhtml_network

  # arangodb:
  #   image: arangodb:3.11.3
  #   container_name: arango_3.11.3_container
  #   restart: always
  #   ports:
  #     - 8529:8529
  #   environment:
  #     - ARANGO_NO_AUTH=1
  #   volumes:
  #     - C:\web\mixhtml\arangodb:/var/lib/arangodb3
  #   networks:
  #     - mixhtml_network

networks:
  mixhtml_network: